export type ApiItemType = 
	"GROUP"
|	"GROUPS" 
|	"DATASETS" // container for datasets within workspace
| 	"DATASET"
| 	"DATASET_XMLA" // only used for QuickPick items to allow to store XMLA information for datasets
|	"REPORTS" // container for reports within workspace
| 	"REPORT"
|	"DATAFLOWS" // container for dataflows within workspace
|	"DATAFLOW"
|	"DASHBOARDS" // container for dashboards within workspace
|	"DASHBOARD"
|	"CAPACITIES"
|	"CAPACITY"
|	"CAPACITYREFRESHABLES"
|	"CAPACITYREFRESHABLE"
|	"CAPACITYWORKLOADS"
|	"CAPACITYWORKLOAD"
|	"GATEWAYS"
|	"GATEWAY"
|	"GATEWAYDATASOURCES"
|	"GATEWAYDATASOURCE"
|	"PIPELINES"
|	"PIPELINE"
|	"PIPELINESTAGES"
|	"PIPELINESTAGE"
|	"PIPELINEOPERATION"
|	"PIPELINEOPERATIONS"
| 	"PIPELINESTAGEDASHBOARD"
| 	"PIPELINESTAGEDATAFLOW"
| 	"PIPELINESTAGEDATAMART"
|	"PIPELINESTAGEDATASET"
|	"PIPELINESTAGEREPORT" 
| 	"PIPELINESTAGEDASHBOARDS"
| 	"PIPELINESTAGEDATAFLOWS"
| 	"PIPELINESTAGEDATAMARTS"
|	"PIPELINESTAGEDATASETS"
|	"PIPELINESTAGEREPORTS" 
|	"DATASETPARAMETERS"
|	"DATASETPARAMETER"
|	"DATASETREFRESHES"			// container for Dataset refreshes
|	"DATASETREFRESH"			// single Dataset refresh
|	"DATAFLOWTRANSACTIONS"		// container for Dataflow refreshes
|	"DATAFLOWTRANSACTION"		// single Dataflow refresh
|	"DATAFLOWDATASOURCES"
|	"DATAFLOWDATASOURCE"
;